# Generated by Django 2.2.12 on 2022-04-16 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragAndDrop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('displayImg', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
