# Generated by Django 2.2.12 on 2022-04-16 08:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dragAndDrop', '0002_auto_20220416_0411'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drop',
            options={'ordering': ['-date']},
        ),
        migrations.RenameField(
            model_name='drop',
            old_name='displayImg',
            new_name='image',
        ),
        migrations.AddField(
            model_name='drop',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
