# Generated by Django 2.2.12 on 2022-04-16 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dragAndDrop', '0003_auto_20220416_0424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drop',
            options={},
        ),
        migrations.RemoveField(
            model_name='drop',
            name='date',
        ),
    ]
